# Number of Ref Ledger pods
replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
  
image:
  repository: gablue316/ref-ledger
  tag: dev-v1.212
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30080

container:
  port: 8080

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

env:
  TZ: America/New_York
  MONGODB_HOST: "host.docker.internal:27017"
  MONGODB_ENV: "local"
  MONGODB_DIRECT_CONNECTION: "true"
  MONGODB_APP_NAME: "ref-ledger-cluster"
  MONGODB_NAME: "refLedger_v2_dev"
  MONGODB_REPLICA_SET: "refLedgerRS"
  LOG_FILE_PATH: "/root/logs/ref-ledgerV2-webServer.log"
  APP_ENV: "development"

cloudflare:
  enabled: false
  replicas: 1
  image:
    repository: cloudflare/cloudflared
    tag: latest
    pullPolicy: IfNotPresent

  tunnelId: 00629144-3807-4593-ac77-24698d2d12cd
  hostname: ref-ledger.com
  credentialsSecret: cloudflared-creds

mongodb:
  host: mongodb
  port: 27017
  database: refLedger_v2

  existingSecret: mongodb-credentials
  usernameKey: username
  passwordKey: password
  
logging:
  level: info

probes:
  liveness:
    path: /
    initialDelaySeconds: 15
    periodSeconds: 20

  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10

nodeSelector: {}

tolerations: []

affinity: {}