apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config

data:
  config.yaml: |
    tunnel: {{ .Values.cloudflare.tunnelId }}

    credentials-file: /creds/credentials.json

    ingress:
      - hostname: {{ .Values.cloudflare.hostname }}
        service: http://ref-ledger:{{ .Values.service.port }}

      - service: http_status:404