apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref-ledger
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ref-ledger
  template:
    metadata:
      labels:
        app: ref-ledger
    spec:
      containers:
      - name: ref-ledger
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
        - name: TZ
          value: "{{ .Values.env.TZ }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name          
        resources:
{{ toYaml .Values.resources | indent 10 }}