apiVersion: v1
kind: Service
metadata:
  name: ref-ledger
spec:
  selector:
    app: ref-ledger
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
{{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{ end }}
  type: {{ .Values.service.type }}