apiVersion: v1
kind: Service
metadata:
  name: ref-ledger
spec:
  selector:
    app: ref-ledger
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  type: {{ .Values.service.type }}