apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config

data:
  config.yaml: |
    tunnel: 00629144-3807-4593-ac77-24698d2d12cd

    credentials-file: /creds/credentials.json

    ingress:
      - hostname: ref-ledger.com
        service: http://ref-ledger:8080

      - service: http_status:404
