---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-creds
  namespace: default
spec:
  encryptedData:
    credentials.json: AgC5UK7opsUaI9raBkJuew5MkubCUgy0hlnwVUXUyStGb798Cq83ivF2j499906vsEYoGlAOZdJ5TCyJDKUczOTaUIyNSqpRZD1F/S6KrBc1U/ttIQZIjJ7XbBcTTZikXLeBItAHMPmrJo6NRRka5Z18zQeGfpzJpPVe98+Xdmt+AvZXogQz6o6Kw1b89qgGN1PMpGmO/iUuoUgNSJqbmxk+7+SR3LMWHgpIPiVdl90Cuw0ef7iv4s8wOXpuLtQeWW3yNpTg/i6E6eAc19FHrwXhzca2Ts3FebTW0aVmmlA70KNyaE+lOXNlT72ApAtyhTBT4iUOGMr2FYip8JgurUSSX6QV3TTTETUBfuxMv2GTPOfr+OGAY2Huh8DsQST3raL46u9sx2Mz3L2e9UtlZGEvn82lztTTD+UmSLChJT+EBJnfEBS9/6yueqFWTSXGwNTIdlxS7PUU/pnBh1/teHzxvi/qaykOVCgJP77fKlXYyEbLwumIscz1TA2Ewwgnwh+uOiC+k9j1EXZpOxy0Y8c/vyNPvVY4qwKYghAQwhYiEupczzeogYSAC26FFt5vukjy1FrWEmaXYJUpi5bl3SL+yJZF6F3RUiYxQe0d8r7QMm6bgVfK+ollSnWsB5UT1Jz3Rgp9OJYu41+JamHURy+YLluoH7BIrC2ryxosiqoY0TWtYKgVk19vL8+pufuIs5b14U3XPM73pLo7v2ZXx07MGAX4EQ8mx42PIvSMQ2v8m63/Ebtb8Nh7FppCgtF0WYm4RsQqGOqeciwqCxSBxYgtGSgcRhZlLUSmnWUVYsqx6QMe+fnke6Q+vPVh09+UE191LmqwPJThShHema4Fi/qhNGMD7yYP6jZvv4JJa+8JYGhbIGK3buY4UVVhBtyb8IpsJWnPkfT8NE/aGWRLUlnOSi23LyZikRj8k+7YRlA+
  template:
    metadata:
      name: cloudflared-creds
      namespace: default
