---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-creds
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCw8+cCtAIBoT4+9KB4Xkk441wZfpsjq2RHcHNMU57jGCjUgQ63+rKVZphP+7ebIiBol6+/HtactklZzE7wOWY8H2pBZKWKDaQ23/C0bUpBAWf0OZCie056vc5P9zwL4wFjuJuTG6zbw0QyPG3l8lJ4la81HOu8rXo0cbVURChPaAfLc/KVDvGqntcB144TsMtPyHry/8aIs+Tcs2srmGk9ncgG4I9ksCvw2jDD2I/0afI8A7Y6uGZVmcqGsOD01AObtIBo7wpYWWX+Qj95+RVbYCxc6fL9ZamPNj59CrL9xvIouIJhj/piqKAP3HTIZuvJekDMXnQRYfHRfiUANCqzrTWWdGfai6F4xwm3h63Yzw7Ld8Mprh3E+AcWoTWLjZmP/eg3clQ9HQ8D5x/A/Y/AO6Xp3+jUOCNqo+uAC3HQR78ByCsFnLU0SRPJBbzR/CSdVNEIx3XlPlvnbHhVlkvUmofz/qpIPPnhSp14+4Oog+SLswjFKxNWuIT8gNqF5nKX7rZojFm1kzmKIRV7H4VJpk9MBqRkojZ9qKv/QqDRgAT5FQ3Nq8RJtYi1Bs/MqiLIbv9IM7QS0om/lk2DxDFNYd18dT6K6nLSfDpnsatuYA9VS1ZC7yDoJgo7bcXxdNid1goaL+K48svxLrYhLB5+qSyUp8VUd/tjay3WRqVUpnZS1BqySUMAujTQLF0IoPqfT0iLbwqQLX3+auytdHIcTTdLKCjh0TrGzqYU4T2ncDJQCN9g7NI4hedvGtDEh+gSUevBekJ3r/7AoOWJ5P5901kylHJG0+yCZRel7NAqGU5GwHKbplWaZ/PKbpTrNXV6ouKmBR6GvJPp6t0Bspd1Z78y10xVUxB1ta+mqAW0GpXnKn4Eqp825bb5nDUKCxANJCTXe/Ys2EA0ctgiMCoAnVttWxxESgSdtsdWZYSp
  template:
    metadata:
      name: cloudflared-creds
      namespace: default
